--PGSERVICE=qwat psql -v ON_ERROR_STOP=on -f ~/Documents/qgis/qwat-sige/export_cartoriviera/export_sql

create schema if not exists cartoriviera;

drop table if exists cartoriviera.qwat_leak;

create table cartoriviera.qwat_leak as
select
leak.id,
    leak.fk_cause,
    leak.fk_pipe,
    leak.widespread_damage,
    leak.detection_date,
    leak.repair_date,
    leak._repaired,
    leak.address,
    leak.pipe_replaced,
    leak.description,
    leak.repair,
    leak.geometry,
    -- leak.label_1_visible,
    -- leak.label_1_x,
    -- leak.label_1_y,
    -- leak.label_1_rotation,
    -- leak.label_1_text,
    -- leak.label_2_visible,
    -- leak.label_2_x,
    -- leak.label_2_y,
    -- leak.label_2_rotation,
    -- leak.label_2_text,
    -- pipe.fk_parent AS pipe_fk_parent,
    -- pipe.fk_function AS pipe_fk_function,
    -- pipe.fk_installmethod AS pipe_fk_installmethod,
    -- pipe.fk_material AS pipe_fk_material,
    -- pipe.fk_distributor AS pipe_fk_distributor,
    -- pipe.fk_precision AS pipe_fk_precision,
    -- pipe.fk_bedding AS pipe_fk_bedding,
    -- pipe.fk_protection AS pipe_fk_protection,
    -- pipe.fk_status AS pipe_fk_status,
    -- pipe.fk_watertype AS pipe_fk_watertype,
    -- pipe.fk_locationtype AS pipe_fk_locationtype,
    -- pipe.fk_folder AS pipe_fk_folder,
    -- pipe.year AS pipe_year,
    -- pipe.year_rehabilitation AS pipe_year_rehabilitation,
    -- pipe.year_end AS pipe_year_end,
    -- pipe.tunnel_or_bridge AS pipe_tunnel_or_bridge,
    -- pipe.pressure_nominal AS pipe_pressure_nominal,
    -- pipe.remark AS pipe_remark,
    -- pipe._valve_count AS pipe__valve_count,
    -- pipe._valve_closed AS pipe__valve_closed,
    -- pipe.schema_force_visible_old AS pipe_schema_force_visible_old,
    -- pipe.fk_node_a AS pipe_fk_node_a,
    -- pipe.fk_node_b AS pipe_fk_node_b,
    -- pipe.fk_district AS pipe_fk_district,
    -- pipe.fk_pressurezone AS pipe_fk_pressurezone,
    -- pipe.fk_printmap AS pipe_fk_printmap,
    -- pipe._length2d AS pipe__length2d,
    -- pipe._length3d AS pipe__length3d,
    -- pipe._diff_elevation AS pipe__diff_elevation,
    -- pipe._printmaps AS pipe__printmaps,
    -- pipe._geometry_alt1_used AS pipe__geometry_alt1_used,
    -- pipe._geometry_alt2_used AS pipe__geometry_alt2_used,
    -- pipe.update_geometry_alt1 AS pipe_update_geometry_alt1,
    -- pipe.update_geometry_alt2 AS pipe_update_geometry_alt2,
    -- pipe.schema_force_visible AS pipe_schema_force_visible,
    -- pipe._schema_visible AS pipe__schema_visible,
    -- pipe.schema_visible AS pipe_schema_visible,
    -- pipe.status_vl_active AS pipe_status_vl_active,
    -- pipe.status_short_fr AS pipe_status_short_fr,
    -- pipe.status_short_en AS pipe_status_short_en,
    -- pipe.status_short_ro AS pipe_status_short_ro,
    -- pipe.status_value_fr AS pipe_status_value_fr,
    -- pipe.status_value_en AS pipe_status_value_en,
    -- pipe.status_value_ro AS pipe_status_value_ro,
    -- pipe.status_description_fr AS pipe_status_description_fr,
    -- pipe.status_description_en AS pipe_status_description_en,
    -- pipe.status_description_ro AS pipe_status_description_ro,
    -- pipe.status_active AS pipe_status_active,
    -- pipe.status_functional AS pipe_status_functional,
    -- pipe.status_code_sire AS pipe_status_code_sire,
    -- pipe.district_name AS pipe_district_name,
    -- pipe.district_shortname AS pipe_district_shortname,
    -- pipe.district_zip AS pipe_district_zip,
    -- pipe.district_land_registry AS pipe_district_land_registry,
    -- pipe.district_prefix AS pipe_district_prefix,
    -- pipe.district_colorcode AS pipe_district_colorcode,
    -- pipe.pressurezone_fk_distributor AS pipe_pressurezone_fk_distributor,
    -- pipe.pressurezone_fk_consumptionzone AS pipe_pressurezone_fk_consumptionzone,
    -- pipe.pressurezone_name AS pipe_pressurezone_name,
    -- pipe.pressurezone_population AS pipe_pressurezone_population,
    -- pipe.pressurezone_subscriber AS pipe_pressurezone_subscriber,
    -- pipe.pressurezone_colorcode AS pipe_pressurezone_colorcode,
    -- pipe.pressurezone__geometry_alt1_used AS pipe_pressurezone__geometry_alt1_used,
    -- pipe.pressurezone__geometry_alt2_used AS pipe_pressurezone__geometry_alt2_used,
    -- pipe.pressurezone_update_geometry_alt1 AS pipe_pressurezone_update_geometry_alt1,
    -- pipe.pressurezone_update_geometry_alt2 AS pipe_pressurezone_update_geometry_alt2,
    -- pipe.installmethod_vl_active AS pipe_installmethod_vl_active,
    -- pipe.installmethod_short_fr AS pipe_installmethod_short_fr,
    -- pipe.installmethod_short_en AS pipe_installmethod_short_en,
    -- pipe.installmethod_short_ro AS pipe_installmethod_short_ro,
    -- pipe.installmethod_value_fr AS pipe_installmethod_value_fr,
    -- pipe.installmethod_value_en AS pipe_installmethod_value_en,
    -- pipe.installmethod_value_ro AS pipe_installmethod_value_ro,
    -- pipe.installmethod_description_fr AS pipe_installmethod_description_fr,
    -- pipe.installmethod_description_en AS pipe_installmethod_description_en,
    -- pipe.installmethod_description_ro AS pipe_installmethod_description_ro,
    -- pipe.precision_vl_active AS pipe_precision_vl_active,
    -- pipe.precision_short_fr AS pipe_precision_short_fr,
    -- pipe.precision_short_en AS pipe_precision_short_en,
    -- pipe.precision_short_ro AS pipe_precision_short_ro,
    -- pipe.precision_value_fr AS pipe_precision_value_fr,
    -- pipe.precision_value_en AS pipe_precision_value_en,
    -- pipe.precision_value_ro AS pipe_precision_value_ro,
    -- pipe.precision_description_fr AS pipe_precision_description_fr,
    -- pipe.precision_description_en AS pipe_precision_description_en,
    -- pipe.precision_description_ro AS pipe_precision_description_ro,
    -- pipe.precision_code_sire AS pipe_precision_code_sire,
    -- pipe.pipe_material_vl_active AS pipe_pipe_material_vl_active,
    -- pipe.pipe_material_short_fr AS pipe_pipe_material_short_fr,
    -- pipe.pipe_material_short_en AS pipe_pipe_material_short_en,
    -- pipe.pipe_material_short_ro AS pipe_pipe_material_short_ro,
    -- pipe.pipe_material_value_fr AS pipe_pipe_material_value_fr,
    -- pipe.pipe_material_value_en AS pipe_pipe_material_value_en,
    -- pipe.pipe_material_value_ro AS pipe_pipe_material_value_ro,
    -- pipe.pipe_material_description_fr AS pipe_pipe_material_description_fr,
    -- pipe.pipe_material_description_en AS pipe_pipe_material_description_en,
    -- pipe.pipe_material_description_ro AS pipe_pipe_material_description_ro,
    -- pipe.pipe_material__displayname_fr AS pipe_pipe_material__displayname_fr,
    -- pipe.pipe_material__displayname_en AS pipe_pipe_material__displayname_en,
    -- pipe.pipe_material__displayname_ro AS pipe_pipe_material__displayname_ro,
    -- pipe.pipe_material_diameter AS pipe_pipe_material_diameter,
    -- pipe.pipe_material_diameter_nominal AS pipe_pipe_material_diameter_nominal,
    -- pipe.pipe_material_diameter_internal AS pipe_pipe_material_diameter_internal,
    -- pipe.pipe_material_diameter_external AS pipe_pipe_material_diameter_external,
    -- pipe.pipe_material_code_sire AS pipe_pipe_material_code_sire,
    -- pipe.pipe_material_pressure_nominal AS pipe_pipe_material_pressure_nominal,
    -- pipe.pipe_material_sdr AS pipe_pipe_material_sdr,
    -- pipe.pipe_material_wall_thickness AS pipe_pipe_material_wall_thickness,
    -- pipe.pipe_material_sn AS pipe_pipe_material_sn,
    -- pipe.pipe_function_vl_active AS pipe_pipe_function_vl_active,
    -- pipe.pipe_function_short_fr AS pipe_pipe_function_short_fr,
    -- pipe.pipe_function_short_en AS pipe_pipe_function_short_en,
    -- pipe.pipe_function_short_ro AS pipe_pipe_function_short_ro,
    -- pipe.pipe_function_value_fr AS pipe_pipe_function_value_fr,
    -- pipe.pipe_function_value_en AS pipe_pipe_function_value_en,
    -- pipe.pipe_function_value_ro AS pipe_pipe_function_value_ro,
    -- pipe.pipe_function_description_fr AS pipe_pipe_function_description_fr,
    -- pipe.pipe_function_description_en AS pipe_pipe_function_description_en,
    -- pipe.pipe_function_description_ro AS pipe_pipe_function_description_ro,
    -- pipe.pipe_function_schema_visible AS pipe_pipe_function_schema_visible,
    -- pipe.pipe_function_major AS pipe_pipe_function_major,
    -- pipe.pipe_function_code_sire AS pipe_pipe_function_code_sire,
    -- pipe.protection_vl_active AS pipe_protection_vl_active,
    -- pipe.protection_short_fr AS pipe_protection_short_fr,
    -- pipe.protection_short_en AS pipe_protection_short_en,
    -- pipe.protection_short_ro AS pipe_protection_short_ro,
    -- pipe.protection_value_fr AS pipe_protection_value_fr,
    -- pipe.protection_value_en AS pipe_protection_value_en,
    -- pipe.protection_value_ro AS pipe_protection_value_ro,
    -- pipe.protection_description_fr AS pipe_protection_description_fr,
    -- pipe.protection_description_en AS pipe_protection_description_en,
    -- pipe.protection_description_ro AS pipe_protection_description_ro,
    -- pipe.distributor_name AS pipe_distributor_name,
    -- pipe.folder_identification AS pipe_folder_identification,
    -- pipe.folder_description AS pipe_folder_description,
    -- pipe.folder_date_start AS pipe_folder_date_start,
    -- pipe.folder_date_end AS pipe_folder_date_end,
    -- pipe.node_b_fk_district AS pipe_node_b_fk_district,
    -- pipe.node_b_fk_pressurezone AS pipe_node_b_fk_pressurezone,
    -- pipe.node_b_fk_printmap AS pipe_node_b_fk_printmap,
    -- pipe.node_b__printmaps AS pipe_node_b__printmaps,
    -- pipe.node_b__geometry_alt1_used AS pipe_node_b__geometry_alt1_used,
    -- pipe.node_b__geometry_alt2_used AS pipe_node_b__geometry_alt2_used,
    -- pipe.node_b__pipe_node_type AS pipe_node_b__pipe_node_type,
    -- pipe.node_b__pipe_orientation AS pipe_node_b__pipe_orientation,
    -- pipe.node_b__pipe_schema_visible AS pipe_node_b__pipe_schema_visible,
    -- pipe.node_b_update_geometry_alt1 AS pipe_node_b_update_geometry_alt1,
    -- pipe.node_b_update_geometry_alt2 AS pipe_node_b_update_geometry_alt2,
    -- pipe.node_a_fk_district AS pipe_node_a_fk_district,
    -- pipe.node_a_fk_pressurezone AS pipe_node_a_fk_pressurezone,
    -- pipe.node_a_fk_printmap AS pipe_node_a_fk_printmap,
    -- pipe.node_a__printmaps AS pipe_node_a__printmaps,
    -- pipe.node_a__geometry_alt1_used AS pipe_node_a__geometry_alt1_used,
    -- pipe.node_a__geometry_alt2_used AS pipe_node_a__geometry_alt2_used,
    -- pipe.node_a__pipe_node_type AS pipe_node_a__pipe_node_type,
    -- pipe.node_a__pipe_orientation AS pipe_node_a__pipe_orientation,
    -- pipe.node_a__pipe_schema_visible AS pipe_node_a__pipe_schema_visible,
    -- pipe.node_a_update_geometry_alt1 AS pipe_node_a_update_geometry_alt1,
    -- pipe.node_a_update_geometry_alt2 AS pipe_node_a_update_geometry_alt2,
    -- cause.vl_active AS cause_vl_active,
    -- cause.short_fr AS cause_short_fr,
    -- cause.short_en AS cause_short_en,
    -- cause.short_ro AS cause_short_ro,
    cause.value_fr AS cause_value_fr
    -- cause.value_en AS cause_value_en,
    -- cause.value_ro AS cause_value_ro,
    -- cause.description_fr AS cause_description_fr,
    -- cause.description_en AS cause_description_en,
    -- cause.description_ro AS cause_description_ro
from qwat_od.vw_export_leak;

alter table cartoriviera.qwat_leak alter column geometry type geometry('point', 21781) using st_force2d(st_geomfromewkb(st_fineltra(geometry, 'chenyx06.chenyx06_triangles', 'the_geom_lv95', 'the_geom_lv03')));
