-- PGSERVICE=qwat_prod psql -v ON_ERROR_STOP=on -f cartoriviera/export_db/qwat_remote.sql

CREATE SCHEMA IF NOT EXISTS usr_cartoriviera;

DROP TABLE IF EXISTS usr_cartoriviera.sige_qgis_qwat_remote;

CREATE TABLE usr_cartoriviera.sige_qgis_qwat_remote AS
SELECT
    id,
    fk_distributor,
    fk_status,
    fk_precision,
    fk_material,
    identification,
    year,
    origin,
    destination,
    folder,
    plan,
    remark,
    sige_cable_installed,
    -- _geometry_alt1_used,
    -- _geometry_alt2_used,
    -- update_geometry_alt1,
    -- update_geometry_alt2,
    geometry,
    -- geometry_alt1,
    -- geometry_alt2,
    label_1_visible,
    label_1_x,
    label_1_y,
    label_1_rotation,
    label_1_text,
    label_2_visible,
    label_2_x,
    label_2_y,
    label_2_rotation,
    label_2_text,
    distributor_name,
    -- status_vl_active,
    -- status_short_fr,
    -- status_short_en,
    -- status_short_ro,
    status_value_fr,
    -- status_value_en,
    -- status_value_ro,
    -- status_description_fr,
    -- status_description_en,
    -- status_description_ro,
    -- status_active,
    -- status_functional,
    -- status_code_sire,
    -- material_vl_active,
    -- material_short_fr,
    -- material_short_en,
    -- material_short_ro,
    material_value_fr
    -- material_value_en,
    -- material_value_ro,
    -- material_description_fr,
    -- material_description_en,
    -- material_description_ro,
    -- material__displayname_fr,
    -- material__displayname_en,
    -- material__displayname_ro,
    -- material_diameter,
    -- material_diameter_nominal,
    -- material_diameter_internal,
    -- material_diameter_external,
    -- material_code_sire,
    -- material_pressure_nominal,
    -- material_sdr,
    -- material_wall_thickness,
    -- material_sn,
    -- precision_vl_active,
    -- precision_short_fr,
    -- precision_short_en,
    -- precision_short_ro,
    -- precision_value_fr,
    -- precision_value_en,
    -- precision_value_ro,
    -- precision_description_fr,
    -- precision_description_en,
    -- precision_description_ro,
    -- precision_code_sire
FROM qwat_od.vw_export_remote;

CREATE INDEX geoidx_sige_qgis_qwat_remote
ON usr_cartoriviera.sige_qgis_qwat_remote
USING gist (geometry);
