-- PGSERVICE=qwat_prod psql -v ON_ERROR_STOP=on -f cartoriviera/export_db/qwat_leak.sql

CREATE SCHEMA IF NOT EXISTS usr_cartoriviera;

DROP TABLE IF EXISTS usr_cartoriviera.sige_qgis_qwat_leak;

CREATE TABLE usr_cartoriviera.sige_qgis_qwat_leak AS
SELECT
    id,
    fk_cause,
    fk_pipe,
    widespread_damage,
    detection_date,
    repair_date,
    _repaired,
    address,
    pipe_replaced,
    description,
    repair,
    geometry,
    -- label_1_visible,
    -- label_1_x,
    -- label_1_y,
    -- label_1_rotation,
    -- label_1_text,
    -- label_2_visible,
    -- label_2_x,
    -- label_2_y,
    -- label_2_rotation,
    -- label_2_text,
    -- pipe_fk_parent,
    -- pipe_fk_function,
    -- pipe_fk_installmethod,
    -- pipe_fk_material,
    -- pipe_fk_distributor,
    -- pipe_fk_precision,
    -- pipe_fk_bedding,
    -- pipe_fk_protection,
    -- pipe_fk_status,
    -- pipe_fk_watertype,
    -- pipe_fk_locationtype,
    -- pipe_fk_folder,
    -- pipe_year,
    -- pipe_year_rehabilitation,
    -- pipe_year_end,
    -- pipe_tunnel_or_bridge,
    -- pipe_pressure_nominal,
    -- pipe_remark,
    -- pipe__valve_count,
    -- pipe__valve_closed,
    -- pipe_schema_force_visible_old,
    -- pipe_fk_node_a,
    -- pipe_fk_node_b,
    -- pipe_fk_district,
    -- pipe_fk_pressurezone,
    -- pipe_fk_printmap,
    -- pipe__length2d,
    -- pipe__length3d,
    -- pipe__diff_elevation,
    -- pipe__printmaps,
    -- pipe__geometry_alt1_used,
    -- pipe__geometry_alt2_used,
    -- pipe_update_geometry_alt1,
    -- pipe_update_geometry_alt2,
    -- pipe_schema_force_visible,
    -- pipe__schema_visible,
    -- pipe_schema_visible,
    -- pipe_status_vl_active,
    -- pipe_status_short_fr,
    -- pipe_status_short_en,
    -- pipe_status_short_ro,
    -- pipe_status_value_fr,
    -- pipe_status_value_en,
    -- pipe_status_value_ro,
    -- pipe_status_description_fr,
    -- pipe_status_description_en,
    -- pipe_status_description_ro,
    -- pipe_status_active,
    pipe_status_functional,
    -- pipe_status_code_sire,
    -- pipe_district_name,
    -- pipe_district_shortname,
    -- pipe_district_zip,
    -- pipe_district_land_registry,
    -- pipe_district_prefix,
    -- pipe_district_colorcode,
    -- pipe_pressurezone_fk_distributor,
    -- pipe_pressurezone_fk_consumptionzone,
    -- pipe_pressurezone_name,
    -- pipe_pressurezone_population,
    -- pipe_pressurezone_subscriber,
    -- pipe_pressurezone_colorcode,
    -- pipe_pressurezone__geometry_alt1_used,
    -- pipe_pressurezone__geometry_alt2_used,
    -- pipe_pressurezone_update_geometry_alt1,
    -- pipe_pressurezone_update_geometry_alt2,
    -- pipe_installmethod_vl_active,
    -- pipe_installmethod_short_fr,
    -- pipe_installmethod_short_en,
    -- pipe_installmethod_short_ro,
    -- pipe_installmethod_value_fr,
    -- pipe_installmethod_value_en,
    -- pipe_installmethod_value_ro,
    -- pipe_installmethod_description_fr,
    -- pipe_installmethod_description_en,
    -- pipe_installmethod_description_ro,
    -- pipe_precision_vl_active,
    -- pipe_precision_short_fr,
    -- pipe_precision_short_en,
    -- pipe_precision_short_ro,
    -- pipe_precision_value_fr,
    -- pipe_precision_value_en,
    -- pipe_precision_value_ro,
    -- pipe_precision_description_fr,
    -- pipe_precision_description_en,
    -- pipe_precision_description_ro,
    -- pipe_precision_code_sire,
    -- pipe_pipe_material_vl_active,
    -- pipe_pipe_material_short_fr,
    -- pipe_pipe_material_short_en,
    -- pipe_pipe_material_short_ro,
    -- pipe_pipe_material_value_fr,
    -- pipe_pipe_material_value_en,
    -- pipe_pipe_material_value_ro,
    -- pipe_pipe_material_description_fr,
    -- pipe_pipe_material_description_en,
    -- pipe_pipe_material_description_ro,
    -- pipe_pipe_material__displayname_fr,
    -- pipe_pipe_material__displayname_en,
    -- pipe_pipe_material__displayname_ro,
    -- pipe_pipe_material_diameter,
    -- pipe_pipe_material_diameter_nominal,
    -- pipe_pipe_material_diameter_internal,
    -- pipe_pipe_material_diameter_external,
    -- pipe_pipe_material_code_sire,
    -- pipe_pipe_material_pressure_nominal,
    -- pipe_pipe_material_sdr,
    -- pipe_pipe_material_wall_thickness,
    -- pipe_pipe_material_sn,
    -- pipe_pipe_function_vl_active,
    -- pipe_pipe_function_short_fr,
    -- pipe_pipe_function_short_en,
    -- pipe_pipe_function_short_ro,
    -- pipe_pipe_function_value_fr,
    -- pipe_pipe_function_value_en,
    -- pipe_pipe_function_value_ro,
    -- pipe_pipe_function_description_fr,
    -- pipe_pipe_function_description_en,
    -- pipe_pipe_function_description_ro,
    -- pipe_pipe_function_schema_visible,
    -- pipe_pipe_function_major,
    -- pipe_pipe_function_code_sire,
    -- pipe_protection_vl_active,
    -- pipe_protection_short_fr,
    -- pipe_protection_short_en,
    -- pipe_protection_short_ro,
    -- pipe_protection_value_fr,
    -- pipe_protection_value_en,
    -- pipe_protection_value_ro,
    -- pipe_protection_description_fr,
    -- pipe_protection_description_en,
    -- pipe_protection_description_ro,
    -- pipe_distributor_name,
    -- pipe_folder_identification,
    -- pipe_folder_description,
    -- pipe_folder_date_start,
    -- pipe_folder_date_end,
    -- pipe_node_b_fk_district,
    -- pipe_node_b_fk_pressurezone,
    -- pipe_node_b_fk_printmap,
    -- pipe_node_b__printmaps,
    -- pipe_node_b__geometry_alt1_used,
    -- pipe_node_b__geometry_alt2_used,
    -- pipe_node_b__pipe_node_type,
    -- pipe_node_b__pipe_orientation,
    -- pipe_node_b__pipe_schema_visible,
    -- pipe_node_b_update_geometry_alt1,
    -- pipe_node_b_update_geometry_alt2,
    -- pipe_node_a_fk_district,
    -- pipe_node_a_fk_pressurezone,
    -- pipe_node_a_fk_printmap,
    -- pipe_node_a__printmaps,
    -- pipe_node_a__geometry_alt1_used,
    -- pipe_node_a__geometry_alt2_used,
    -- pipe_node_a__pipe_node_type,
    -- pipe_node_a__pipe_orientation,
    -- pipe_node_a__pipe_schema_visible,
    -- pipe_node_a_update_geometry_alt1,
    -- pipe_node_a_update_geometry_alt2,
    -- cause_vl_active,
    -- cause_short_fr,
    -- cause_short_en,
    -- cause_short_ro,
    cause_value_fr
    -- cause_value_en,
    -- cause_value_ro,
    -- cause_description_fr,
    -- cause_description_en,
    -- cause_description_ro
FROM qwat_od.vw_export_leak;

ALTER TABLE usr_cartoriviera.sige_qgis_qwat_leak ALTER COLUMN geometry TYPE geometry('point', 2056) USING ST_Force2D(geometry);

CREATE INDEX geoidx_sige_qgis_qwat_leak
ON usr_cartoriviera.sige_qgis_qwat_leak
USING gist (geometry);
